
const ListOfProducts = [
    {
        id : 5,
        name: "Instant Pot Duo Plus, 6-Quart Whisper",
        src: "./src/components/assets/product/headset.png",
        review: "./src/components/assets/stars.png",
        stock: "21 left in stock",
        price: "$31.88",
        catagory: "Electronics",
      },
    {
        id: 0,
      src: "./src/components/assets/product/shoeW.png",
      name: "White AirForce 1’s, size 7-9",
      review: "./src/components/assets/star.png",
      price: "$112.55",
      stock: "21 left in stock",
      catagory: "Shoes",
    },
    {
        id: 1,
      src: "./src/components/assets/product/shoeB.png",
      name: "Oxford shoe - Black- sam",
      review: "./src/components/assets/star.png",
      price: "$300.45",
      stock: "not available in stock",
      catagory: "Shoes",
    },
    {
        id: 2,
      src: "./src/components/assets/product/shoe.png",
      name: "Air Jordan 1’s",
      review: "./src/components/assets/stars.png",
      price: "$220.55",
      stock: "50 pair left in stock",
        catagory: "Shoes",
    },
    {
        id: 3,
      src: "./src/components/assets/product/shoeWB.png",
      name: "Jordan 4 - Military Blue",
      price: "$400",
      review: "./src/components/assets/star.png",
      suggestion: true,
      stock: "10 pair left in stock",
        catagory: "Shoes",
    },
    {
        id: 4,
      src: "./src/components/assets/product/shoeBW.png",
      name: "New Balance - Runners-Men",
      review: "./src/components/assets/stars.png",
      price: "$92.88",
      stock: "21 left in stock",
        suggestion: true,
            catagory: "Shoes",
    },
    {
        id : 5,
        name: "Instant Pot Duo Plus, 6-Quart Whisper",
        src: "./src/components/assets/product/headset.png",
        review: "./src/components/assets/stars.png",
        stock: "21 left in stock",
        price: "$31.88",
        suggestion: true,
        catagory: "Electronics",
      },
      {
        id : 6,
        name: "INIU Portable Charger",
        src: "./src/components/assets/product/powerBank.png",
        price: "$18.90",
        review: "./src/components/assets/star.png",
        stock: "Not available in stock",
        suggestion: true,
        catagory: "Electronics",
      },
      {
        id : 7,
        name: "Philips Viva Collection SoupMaker",
        src: "./src/components/assets/product/pan.png",
        price: "$8.90",
        review: "./src/components/assets/stars.png",
        stock: "19 left in stock",
        suggestion: true,
        catagory: "Household",
      },
      {
        id : 8,
        name: "Sunbeam Steammaster 1400 Watt Iron",
        src: "./src/components/assets/product/iron.png",
        price: "$18.88",
        review: "./src/components/assets/star.png",
        stock: "Re-stocked soon",
        suggestion: true,
        catagory: "Household",
      },
      {
        id : 9,
        name: "VIZIO 32-inch HD Smart TV 720p LED",
        src: "./src/components/assets/product/desktop.png",
        price: "$80.33",
        review: "./src/components/assets/stars.png",
        stock: "Re-stocked soon",
        suggestion: true,
        catagory: "Electronics",
      },
  ];
  
 
  export default ListOfProducts   ;

